### PR TITLE
Added `pip` install usage in `readme.md` and added other docstrings for ease of access for users.

### PR DESCRIPTION
**Pull request by hemangjoshi37a**

### CODE REVIEW

**Comment by phillmac** [comment]
LGTM, is this ready to merge?

**Comment by hemangjoshi37a** [comment]
> LGTM, is this ready to merge?

Everything checked, ready to merge.

**Comment by hemangjoshi37a** [comment]
If you give me `write access` I want to develop this library for full time. I think this repo has very great hidden potential.

I also want to develop further similar implementation for `dart` or `Flutter and `React` in near coming future. I am really optimistic about this.

**Comment by hemangjoshi37a** [comment]
Actully if this goes well then may be I will transform most of my application that are using centralized databases to orbitDB. I saw the youtube video about one operson making a chat Dapp that uses orbitDB as database backend and it was really fascinating to me how smoothly it works. Only thing we need to do is add some user accessibility and clear documentation so that everyone can get onboad very easily. The only thing that many libraries lack that are very great otherwise are user retention. And this can be achieve by making the user onboarding much more easier.

**Comment by phillmac** [comment]
I don't have full org access to this to hand out write perms, if you make a few more PRs I think I can make a case for getting you on the team.

**Pull request merged**
